msfo_records/forms.py
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired
from flask_wtf import FlaskForm


class Record_form(FlaskForm):
    company_name = StringField('Название компании: ', validators=[DataRequired()])
    short_info = TextAreaField('Краткий отчёт: ')
    long_info = StringField('Ссылка на полный отчёт: ', validators=[DataRequired()])
    

msfo_records/content_blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for
from models import Records
from .forms import Record_form
from app import data_base
from datetime import datetime, timedelta
from flask_security import login_required, roles_accepted, current_user


# блюпринт кусок изолированной функциональности
# record обработчик блюпринта
# аргументы: название блюпринта, приложение, и путь к шаблонам
msfo_records = Blueprint('msfo_records', __name__, template_folder='templates')



# страница представления контента(таблицы)
@msfo_records.route('/', methods=['POST', 'GET'])
def index():
    # добавление компании.
    if request.method == 'POST' and (current_user.has_role('editor') or current_user.has_role('admin')):
        company_name = request.form['company_name']
        short_info = request.form['short_info']
        long_info = request.form['long_info']
        try:
            record = Records(company_name=company_name, short_info=short_info, long_info=long_info)
            data_base.session.add(record)
            data_base.session.commit()
        except:
            data_base.session.rollback()
            print('Ошибка записи в базу данных.')
        return redirect( url_for('msfo_records.index') )
    form = Record_form()

    # принимаем в переменную page объект request со значениями из фронтенда
    page = request.args.get('page')
    # проверка значения переменной page, если переменная не пустая и является цифрой,
    # тогда приводим её к целочисленному типу, иначе страница будет первой
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    # в переменную search считывается то, что пользователь ввёл в строку поиска
    search = request.args.get('search')
    # Условие: если переменная search содержит что - либо, тогда у класса Records - модели запросов в б.д.
    # запрашиваем данные по сравниванию пользовательского запроса с именами компаний или содержанию краткого отчёта
    if search:
        msfo_records = Records.query.filter(Records.company_name.contains(search) |
                                       Records.short_info.contains(search)).order_by(Records.updated.desc())
    # иначе рендерится страница со всеми записями
    else:
        msfo_records = Records.query.order_by(Records.updated.desc())

    # msfo_records является объектом BaseQuery одним из его методов является paginate()
    # он принимает три именованых аргумента: 1- номер страницы
    # 2- количество записей из б.д. (сколько записей будет на каждой странице, установил пока что 5)
    # 3- error_out(можно не указывать явно) - установлен по умолчанию в True, сигнализирует об ошибках
    pages = msfo_records.paginate(page=page, per_page=5)
    return render_template('msfo_records/index.html', form=form, pages=pages, search=search)

# роут для формы редактирования записи
@msfo_records.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
@roles_accepted('admin', 'editor')
def edit_record(slug):
    # получаем данные конкретной компании по слагу
    record = Records.query.filter(Records.slug == slug).first_or_404()
    # добавил отдельно обновление даты т.к. в формах дата не указывается, а генерится автоматически.
    record.updated = datetime.utcnow()+timedelta(hours=3)
    # при пост запросе получаем в форму html данные из объекта record
    if request.method == 'POST':
        form = Record_form(formdata=request.form, obj=record)
        # метод populate_obj заменяет новыми данными поля формы
        form.populate_obj(record)
        # комит для б.д. чтобы сохранить изменения
        data_base.session.commit()
        return redirect( url_for('msfo_records.index', slug=record.slug) )

    form = Record_form(obj=record)
    return render_template('msfo_records/edit_record.html', record=record, form=form)


# поиск по слагу в б.д. <...> - это переменная динамической ссылки
@msfo_records.route('/<slug>')
def record_detail(slug):
    # query.filter может выдать запрос списком если нашлось несколько результатов,
    # так как слаг уникальный, то берём первый попавшийся результат ( метод .first() )
    record = Records.query.filter(Records.slug == slug).first_or_404()
    # возвращается страница с детальной информацией о компании
    return render_template('msfo_records/record_detail.html', record=record)

msfo_records/templates/msfo_records/edit_record.html
{% extends 'base.html' %}


{% block title %}

    Редактировать.

{% endblock %}

{% block content_title %}

    Редактировать/обновить информацию.

{% endblock %}



{% block add_company_form %}
<!-- параметр slug передаётся в функцию edit_record( slug ) -->
<form action="{{ url_for('msfo_records.edit_record', slug=record.slug) }}" method="POST">

    {% for field in form if field.name not in ['csrf_token'] %}
    <div>
        {{ field.label(class="control-label") }}
        {{ field(class="form-control") }}<br>
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-outline-success">Обновить</button>

</form>
{% endblock %}> 

msfo_records/templates/msfo_records/index.html
{% extends 'base.html' %}


{% block title %}
Таблица отчётов.
{% endblock %}

{% block content_title %}
Таблица отчётов МСФО/РСБУ.
{% endblock %}


{% block add_company_form %}

<!-- объект current_user в шаблонизаторе по умолчанию, метод has_role() в классе UserMixin (models.py) -->

{% if current_user.has_role('admin') or current_user.has_role('editor') %}

<!-- циклом выводятся поля формы из бэка, в скобках можно каждому полю присвоить класс из CSS стилей -->

<form action="{{ url_for('msfo_records.index')}}" method="POST">
    {% for field in form if field.name not in ['csrf_token'] %}
        {{ field.label(class="control-label") }}
        {{ field(class="form-control") }}<br>
    {% endfor %}
    <button type="submit" class="btn btn-outline-success">Добавить</button>
</form>

{% endif %}

{% endblock %}




{% block content %}

<table class="table">
    <thead>
    <tr>
        <th scope="col">Компания</th>
        {% if current_user.has_role('admin') or current_user.has_role('editor')%}
            <th scope="col"></th>
        {% endif %}
        <th scope="col">Краткий отчёт</th>
        <th scope="col">Ссылка на полный отчёт</th>
        <th scope="col">Дата обновления</th>
    </tr>
    </thead>

    <tbody>

    <!-- циклом выводятся записи из б.д. постранично, записи берутся из объекта pages-->

    {% for record in pages.items %}

    <!-- на название компании навешивается ссылка, которая переадресует на страницу record_detail.html,
    для этого в функцию record_detail из вью msfo_records передаёт аргумент slug которому присваивается значение
    поля slug объекта record, перейдя по ссылке мы попадём на страницу детальной информации о компании -->
    <tr>
        <td class="col-1"><a href="{{ url_for('msfo_records.record_detail', slug=record.slug) }}">
            {{ record.company_name }}</a>
        </td>
        {% if current_user.has_role('admin') or current_user.has_role('editor') %}
        <td class="col-1">
            <button id={{record.slug}}
                    class="btn btn-outline-success"

                    onclick='window.location.href="{{ url_for('msfo_records.edit_record', slug=record.slug) }}"' method="POST">
                    Редактировать
            </button>
        </td>
        {% endif %}
        <td class="col-6"><textarea readonly class="col-12 short_info"> {{ record.short_info }}</textarea></td>
        <td class="col-3"><a href="{{ record.long_info }}">полный отчёт</a></td>

        <!--тут небольшое форматирование вывода даты, мне удобно в формате: день.месяц.год
            можно настроить в любом удобном формате-->
        <td class="col-1"> {{ record.updated.strftime("%H:%M:%S %d.%m.%Y") }}</td>
    </tr>

    {% endfor %}
    </tbody>
</table>


<!-- Пагинация -->
<nav aria-label="Page navigation example">
    <ul class="pagination pagination-lg">

        <!-- Проработка кнопки "предыдущая страница".
        Условие: если метод has_prev объекта pages - пуст, тогда проявить class="page-item disabled"  -->
        <li {% if not pages.has_prev %} class="page-item disabled"  {% endif %}>
            <!-- ссылка адресует на страницу из метода prev_num(он динамический) -->
            <a class="page-link" href="{{ url_for('msfo_records.index',search=search, page=pages.prev_num) }}"
               aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>

        <!-- тут циклом выводятся номера страниц из объекта pages методом-итератором iter_pages()
        этот метод может принимать 4 аргумента, у них есть дефолтные значения,
        они проявятся если страниц будет слишком много, например появятся многоточия и разделения по количеству страниц
        до и после многоточия, задав значения аргументов можно регулировать как удобно. -->

        {% for page in pages.iter_pages(left_edge=2,right_edge=2,left_current=1, right_current=2) %}
        {% if page %}
        <!-- Проверка является ли page текущей страницей, если да, то проявить class="page-item active" -->
        <li {% if page == pages.page %} class="page-item active" {% endif %}>
            <a class="page-link" href="{{ url_for('msfo_records.index', search=search, page=page) }}">{{ page }}</a>
        </li>
        {% else %}
        <li class="page-item"><a class="page-link">...</a></li>
        {% endif %}
        {% endfor %}

        <!-- Проработка кнопки "следующая страница".
          Делается по аналогии кнопки "предыдущая страница" только зеркально  -->

        <li {% if pages.has_next %} class="page-item"  {% else %} class="page-item disabled" {% endif %}>
            <a class="page-link"  href="{{ url_for('msfo_records.index',search=search, page=pages.next_num) }}"
               aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>

    </ul>
</nav>
{% endblock %}

msfo_records/templates/msfo_records/record_detail.html
{% extends 'base.html' %}



{% block title %}

    {{ record.company_name }}

{% endblock %}


{% block content_title %}

    {{ record.company_name }}

{% endblock %}



{% block content %}

<table class="table">
    <td class="col-1">ID:</td><td> {{ record.id }}</td>
    <tr>
    <td style="vertical-align: top";>Краткий отчёт</td><td class="col-1">{{ record.short_info }}</td>
    <tr>
    <td>Ссылка на полный отчёт</td><td class="col-1"><a href="{{ record.long_info }}">{{ record.long_info }}</a></td>
    <tr>
    <td>Дата обновления</td><td class="col-1">{{ record.updated.strftime("%d.%m.%Y %H:%M") }}</td>
</table>

{% endblock %}